[default_session]
preview_command = "eza -la --all --git --icons --color=always {}"

[[session]]
name = "Notes"
path = "~/obsidian-vault/"
startup_command = 'nvim +GoToFile'

[[session]]
name = "Home (~)"
path = "~/"

[[session]]
name = "Config"
path = "~/.config/"
startup_command = 'nvim +GoToFile'

[[session]]
name = "Workspace"
path = "~/workspace/"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Dotfiles"
path = "~/workspace/dotfiles/"
startup_command = "nvim +GoToFile"

[[session]]
name = "LazySQL Config"
path = "~/Library/Application Support/lazysql"
startup_command = "nvim config.toml"
preview_command = "bat --language=bash --style=snip --color=always ~/Library/Application Support/lazysql/config.toml"

[[session]]
name = "Rss Feeds"
path = "~/.newsboat/"
startup_command = "newsboat -r"
preview_command = "bat --language=bash --style=snip --color=always ~/.newsboat/urls"


[[session]]
name = "Presents"
path = "~/Documents/presents"
startup_command = "nvim +GoToFile"
